/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 Receive Data Source Select: UART_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 Transmit Data Source Select: UART0_TX pin */

/*! @name PORTA1 (number 35), J1[2]/D0/UART1_RX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTA2 (number 36), J1[4]/D1/UART1_TX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTE31 (number 28), SSG
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SSG_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SSG_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SSG_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SSG_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SSG_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SSG_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTE18 (number 16), SSE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SSE_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SSE_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SSE_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SSE_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SSE_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SSE_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTE19 (number 17), SSF
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SSF_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SSF_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SSF_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SSF_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SSF_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SSF_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTE17 (number 15), SSD
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SSD_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SSD_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SSD_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SSD_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SSD_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SSD_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTE16 (number 14), SSB
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SSB_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SSB_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SSB_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SSB_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SSB_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SSB_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTE6 (number 7), SSA
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SSA_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SSA_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SSA_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SSA_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SSA_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SSA_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTE3 (number 4), SSC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SSC_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SSC_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SSC_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SSC_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SSC_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SSC_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTE2 (number 3), SSDP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SSDP_FGPIO FGPIOE             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SSDP_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SSDP_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SSDP_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SSDP_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SSDP_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC1 (number 71), SW_1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW_1_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SW_1_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW_1_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW_1_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW_1_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW_1_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTC2 (number 72), SW_2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW_2_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SW_2_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW_2_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW_2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW_2_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW_2_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTB3 (number 56), SW_3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW_3_FGPIO FGPIOB             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SW_3_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW_3_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW_3_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW_3_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW_3_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
